#!/bin/bash
LAST_SNAP="$(qemu-img snapshot -l debian-stable-qemu-aarch64/sys_boot.img|tail -n1|awk '{print $2}')"

echo LAST_SNAP: "$LAST_SNAP"

function onSIGUSR1
{
    echo "$0: timeout: savevm"
    echo "savevm Z"|./mon-cmd
    sleep 10
    echo "$0: timeout: quit"
    echo "quit"|./mon-cmd
    exit 0
}

trap onSIGUSR1 USR1

echo ./run-sys "Last snapshot: $LAST_SNAP"
./run-sys "$LAST_SNAP" &
wait $!
echo "$0: end"
